### PR TITLE
Fix onupdate

### LINKED ISSUE #84: this.selectedMailbox vs this._selectedMailbox
emailjs-imap-client.js sometimes uses `this.selectedMailbox` and sometimes `this._selectedMailbox`. Pretty sure this is a bug.

### PR DESCRIPTION
**Pull request by c-f-h**
In the code calling the `onupdate` callback, `selectedMailbox` was being used instead of `_selectedMailbox`, which is undefined.

I extended the `#deleteMessages` integration test to show this problem, fixed the bug and fixed the unit tests which relied on the faulty behavior. I also cleaned up some of the integration tests using promises while I was there.

Fixes #84.

### CODE REVIEW

File: test/integration/emailjs-imap-client-test.js [hunk 1]
```diff
@@ -327,27 +333,27 @@
                     }).then(() => {
                         return imap.selectMailbox('inbox');
                     }).then((resultInfo) => {
-                        expect(initialInfo.exists !== resultInfo.exists).to.be.true;
-                    }).then(done).catch(done);
+                        expect(initialInfo.exists - 1 === resultInfo.exists).to.be.true;
```
Comment (felixhammerl) [inline test/integration/emailjs-imap-client-test.js]: uhm ... that -1 looks wrong?

**Comment by felixhammerl** [comment]
thanks! good catch, i probably screwed that up during the refactoring... the one thing you don't unit test, you break :-/

File: test/integration/emailjs-imap-client-test.js (hunk 1 above)
Comment (c-f-h) [inline test/integration/emailjs-imap-client-test.js]: Why? Initial number minus one deleted gives final number. It passes, at least ;)

Comment (felixhammerl) [inline test/integration/emailjs-imap-client-test.js]: omg sorry i was still asleep apparently -.-
